version: '3'

volumes:
  redis-data:
  mongo-data:

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: evetools
      MONGO_INITDB_ROOT_PASSWORD: evetools
      MONGO_INITDB_DATABASE: evetools
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  asyncq:
    image: hibiken/asynqmon
    ports:
      - 8080:8080
    environment:
      REDIS_ADDR: redis:6379
      REDIS_DB: 10

#  scheduler:
#    image: scheduler
#    build:
#      context: .
#      dockerfile: deployments/scheduler/Dockerfile
#    ports:
#      - 3333:3000
#    environment:
#      PORT: 3000
