// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package database

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/buckbrady/evebot-tools-backend/pkg/model"
)

func newCharacterPortrait(db *gorm.DB, opts ...gen.DOOption) characterPortrait {
	_characterPortrait := characterPortrait{}

	_characterPortrait.characterPortraitDo.UseDB(db, opts...)
	_characterPortrait.characterPortraitDo.UseModel(&model.CharacterPortrait{})

	tableName := _characterPortrait.characterPortraitDo.TableName()
	_characterPortrait.ALL = field.NewAsterisk(tableName)
	_characterPortrait.ID = field.NewInt32(tableName, "id")
	_characterPortrait.Px128x128 = field.NewString(tableName, "px128x128")
	_characterPortrait.Px256x256 = field.NewString(tableName, "px256x256")
	_characterPortrait.Px512x512 = field.NewString(tableName, "px512x512")
	_characterPortrait.Px64x64 = field.NewString(tableName, "px64x64")

	_characterPortrait.fillFieldMap()

	return _characterPortrait
}

type characterPortrait struct {
	characterPortraitDo characterPortraitDo

	ALL       field.Asterisk
	ID        field.Int32
	Px128x128 field.String
	Px256x256 field.String
	Px512x512 field.String
	Px64x64   field.String

	fieldMap map[string]field.Expr
}

func (c characterPortrait) Table(newTableName string) *characterPortrait {
	c.characterPortraitDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c characterPortrait) As(alias string) *characterPortrait {
	c.characterPortraitDo.DO = *(c.characterPortraitDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *characterPortrait) updateTableName(table string) *characterPortrait {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt32(table, "id")
	c.Px128x128 = field.NewString(table, "px128x128")
	c.Px256x256 = field.NewString(table, "px256x256")
	c.Px512x512 = field.NewString(table, "px512x512")
	c.Px64x64 = field.NewString(table, "px64x64")

	c.fillFieldMap()

	return c
}

func (c *characterPortrait) WithContext(ctx context.Context) *characterPortraitDo {
	return c.characterPortraitDo.WithContext(ctx)
}

func (c characterPortrait) TableName() string { return c.characterPortraitDo.TableName() }

func (c characterPortrait) Alias() string { return c.characterPortraitDo.Alias() }

func (c characterPortrait) Columns(cols ...field.Expr) gen.Columns {
	return c.characterPortraitDo.Columns(cols...)
}

func (c *characterPortrait) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *characterPortrait) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 5)
	c.fieldMap["id"] = c.ID
	c.fieldMap["px128x128"] = c.Px128x128
	c.fieldMap["px256x256"] = c.Px256x256
	c.fieldMap["px512x512"] = c.Px512x512
	c.fieldMap["px64x64"] = c.Px64x64
}

func (c characterPortrait) clone(db *gorm.DB) characterPortrait {
	c.characterPortraitDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c characterPortrait) replaceDB(db *gorm.DB) characterPortrait {
	c.characterPortraitDo.ReplaceDB(db)
	return c
}

type characterPortraitDo struct{ gen.DO }

func (c characterPortraitDo) Debug() *characterPortraitDo {
	return c.withDO(c.DO.Debug())
}

func (c characterPortraitDo) WithContext(ctx context.Context) *characterPortraitDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c characterPortraitDo) ReadDB() *characterPortraitDo {
	return c.Clauses(dbresolver.Read)
}

func (c characterPortraitDo) WriteDB() *characterPortraitDo {
	return c.Clauses(dbresolver.Write)
}

func (c characterPortraitDo) Session(config *gorm.Session) *characterPortraitDo {
	return c.withDO(c.DO.Session(config))
}

func (c characterPortraitDo) Clauses(conds ...clause.Expression) *characterPortraitDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c characterPortraitDo) Returning(value interface{}, columns ...string) *characterPortraitDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c characterPortraitDo) Not(conds ...gen.Condition) *characterPortraitDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c characterPortraitDo) Or(conds ...gen.Condition) *characterPortraitDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c characterPortraitDo) Select(conds ...field.Expr) *characterPortraitDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c characterPortraitDo) Where(conds ...gen.Condition) *characterPortraitDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c characterPortraitDo) Order(conds ...field.Expr) *characterPortraitDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c characterPortraitDo) Distinct(cols ...field.Expr) *characterPortraitDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c characterPortraitDo) Omit(cols ...field.Expr) *characterPortraitDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c characterPortraitDo) Join(table schema.Tabler, on ...field.Expr) *characterPortraitDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c characterPortraitDo) LeftJoin(table schema.Tabler, on ...field.Expr) *characterPortraitDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c characterPortraitDo) RightJoin(table schema.Tabler, on ...field.Expr) *characterPortraitDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c characterPortraitDo) Group(cols ...field.Expr) *characterPortraitDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c characterPortraitDo) Having(conds ...gen.Condition) *characterPortraitDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c characterPortraitDo) Limit(limit int) *characterPortraitDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c characterPortraitDo) Offset(offset int) *characterPortraitDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c characterPortraitDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *characterPortraitDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c characterPortraitDo) Unscoped() *characterPortraitDo {
	return c.withDO(c.DO.Unscoped())
}

func (c characterPortraitDo) Create(values ...*model.CharacterPortrait) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c characterPortraitDo) CreateInBatches(values []*model.CharacterPortrait, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c characterPortraitDo) Save(values ...*model.CharacterPortrait) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c characterPortraitDo) First() (*model.CharacterPortrait, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CharacterPortrait), nil
	}
}

func (c characterPortraitDo) Take() (*model.CharacterPortrait, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CharacterPortrait), nil
	}
}

func (c characterPortraitDo) Last() (*model.CharacterPortrait, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CharacterPortrait), nil
	}
}

func (c characterPortraitDo) Find() ([]*model.CharacterPortrait, error) {
	result, err := c.DO.Find()
	return result.([]*model.CharacterPortrait), err
}

func (c characterPortraitDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CharacterPortrait, err error) {
	buf := make([]*model.CharacterPortrait, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c characterPortraitDo) FindInBatches(result *[]*model.CharacterPortrait, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c characterPortraitDo) Attrs(attrs ...field.AssignExpr) *characterPortraitDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c characterPortraitDo) Assign(attrs ...field.AssignExpr) *characterPortraitDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c characterPortraitDo) Joins(fields ...field.RelationField) *characterPortraitDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c characterPortraitDo) Preload(fields ...field.RelationField) *characterPortraitDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c characterPortraitDo) FirstOrInit() (*model.CharacterPortrait, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CharacterPortrait), nil
	}
}

func (c characterPortraitDo) FirstOrCreate() (*model.CharacterPortrait, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CharacterPortrait), nil
	}
}

func (c characterPortraitDo) FindByPage(offset int, limit int) (result []*model.CharacterPortrait, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c characterPortraitDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c characterPortraitDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c characterPortraitDo) Delete(models ...*model.CharacterPortrait) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *characterPortraitDo) withDO(do gen.Dao) *characterPortraitDo {
	c.DO = *do.(*gen.DO)
	return c
}
