// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package database

import (
	"context"
	"fmt"
	"testing"

	"github.com/buckbrady/evebot-tools-backend/pkg/model"
	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
)

func init() {
	InitializeDB()
	err := db.AutoMigrate(&model.Contract{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&model.Contract{}) fail: %s", err)
	}
}

func Test_contractQuery(t *testing.T) {
	contract := newContract(db)
	contract = *contract.As(contract.TableName())
	_do := contract.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(contract.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <contract> fail:", err)
		return
	}

	_, ok := contract.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from contract success")
	}

	err = _do.Create(&model.Contract{})
	if err != nil {
		t.Error("create item in table <contract> fail:", err)
	}

	err = _do.Save(&model.Contract{})
	if err != nil {
		t.Error("create item in table <contract> fail:", err)
	}

	err = _do.CreateInBatches([]*model.Contract{{}, {}}, 10)
	if err != nil {
		t.Error("create item in table <contract> fail:", err)
	}

	_, err = _do.Select(contract.ALL).Take()
	if err != nil {
		t.Error("Take() on table <contract> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <contract> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <contract> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <contract> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*model.Contract{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <contract> fail:", err)
	}

	_, err = _do.Select(contract.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <contract> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <contract> fail:", err)
	}

	_, err = _do.Select(contract.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <contract> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <contract> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <contract> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <contract> fail:", err)
	}

	_, err = _do.ScanByPage(&model.Contract{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <contract> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <contract> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <contract> fail:", err)
	}

	var _a _another
	var _aPK = field.NewString(_a.TableName(), "id")

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <contract> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <contract> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <contract> fail:", err)
	}
}
