// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package database

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/buckbrady/evebot-tools-backend/pkg/model"
)

func newCorporationAllianceHistory(db *gorm.DB, opts ...gen.DOOption) corporationAllianceHistory {
	_corporationAllianceHistory := corporationAllianceHistory{}

	_corporationAllianceHistory.corporationAllianceHistoryDo.UseDB(db, opts...)
	_corporationAllianceHistory.corporationAllianceHistoryDo.UseModel(&model.CorporationAllianceHistory{})

	tableName := _corporationAllianceHistory.corporationAllianceHistoryDo.TableName()
	_corporationAllianceHistory.ALL = field.NewAsterisk(tableName)
	_corporationAllianceHistory.ID = field.NewInt32(tableName, "id")
	_corporationAllianceHistory.AllianceID = field.NewInt32(tableName, "alliance_id")
	_corporationAllianceHistory.IsDeleted = field.NewBool(tableName, "is_deleted")
	_corporationAllianceHistory.RecordID = field.NewInt32(tableName, "record_id")
	_corporationAllianceHistory.StartDate = field.NewTime(tableName, "start_date")

	_corporationAllianceHistory.fillFieldMap()

	return _corporationAllianceHistory
}

type corporationAllianceHistory struct {
	corporationAllianceHistoryDo corporationAllianceHistoryDo

	ALL        field.Asterisk
	ID         field.Int32
	AllianceID field.Int32
	IsDeleted  field.Bool
	RecordID   field.Int32
	StartDate  field.Time

	fieldMap map[string]field.Expr
}

func (c corporationAllianceHistory) Table(newTableName string) *corporationAllianceHistory {
	c.corporationAllianceHistoryDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c corporationAllianceHistory) As(alias string) *corporationAllianceHistory {
	c.corporationAllianceHistoryDo.DO = *(c.corporationAllianceHistoryDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *corporationAllianceHistory) updateTableName(table string) *corporationAllianceHistory {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt32(table, "id")
	c.AllianceID = field.NewInt32(table, "alliance_id")
	c.IsDeleted = field.NewBool(table, "is_deleted")
	c.RecordID = field.NewInt32(table, "record_id")
	c.StartDate = field.NewTime(table, "start_date")

	c.fillFieldMap()

	return c
}

func (c *corporationAllianceHistory) WithContext(ctx context.Context) *corporationAllianceHistoryDo {
	return c.corporationAllianceHistoryDo.WithContext(ctx)
}

func (c corporationAllianceHistory) TableName() string {
	return c.corporationAllianceHistoryDo.TableName()
}

func (c corporationAllianceHistory) Alias() string { return c.corporationAllianceHistoryDo.Alias() }

func (c corporationAllianceHistory) Columns(cols ...field.Expr) gen.Columns {
	return c.corporationAllianceHistoryDo.Columns(cols...)
}

func (c *corporationAllianceHistory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *corporationAllianceHistory) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 5)
	c.fieldMap["id"] = c.ID
	c.fieldMap["alliance_id"] = c.AllianceID
	c.fieldMap["is_deleted"] = c.IsDeleted
	c.fieldMap["record_id"] = c.RecordID
	c.fieldMap["start_date"] = c.StartDate
}

func (c corporationAllianceHistory) clone(db *gorm.DB) corporationAllianceHistory {
	c.corporationAllianceHistoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c corporationAllianceHistory) replaceDB(db *gorm.DB) corporationAllianceHistory {
	c.corporationAllianceHistoryDo.ReplaceDB(db)
	return c
}

type corporationAllianceHistoryDo struct{ gen.DO }

func (c corporationAllianceHistoryDo) Debug() *corporationAllianceHistoryDo {
	return c.withDO(c.DO.Debug())
}

func (c corporationAllianceHistoryDo) WithContext(ctx context.Context) *corporationAllianceHistoryDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c corporationAllianceHistoryDo) ReadDB() *corporationAllianceHistoryDo {
	return c.Clauses(dbresolver.Read)
}

func (c corporationAllianceHistoryDo) WriteDB() *corporationAllianceHistoryDo {
	return c.Clauses(dbresolver.Write)
}

func (c corporationAllianceHistoryDo) Session(config *gorm.Session) *corporationAllianceHistoryDo {
	return c.withDO(c.DO.Session(config))
}

func (c corporationAllianceHistoryDo) Clauses(conds ...clause.Expression) *corporationAllianceHistoryDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c corporationAllianceHistoryDo) Returning(value interface{}, columns ...string) *corporationAllianceHistoryDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c corporationAllianceHistoryDo) Not(conds ...gen.Condition) *corporationAllianceHistoryDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c corporationAllianceHistoryDo) Or(conds ...gen.Condition) *corporationAllianceHistoryDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c corporationAllianceHistoryDo) Select(conds ...field.Expr) *corporationAllianceHistoryDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c corporationAllianceHistoryDo) Where(conds ...gen.Condition) *corporationAllianceHistoryDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c corporationAllianceHistoryDo) Order(conds ...field.Expr) *corporationAllianceHistoryDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c corporationAllianceHistoryDo) Distinct(cols ...field.Expr) *corporationAllianceHistoryDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c corporationAllianceHistoryDo) Omit(cols ...field.Expr) *corporationAllianceHistoryDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c corporationAllianceHistoryDo) Join(table schema.Tabler, on ...field.Expr) *corporationAllianceHistoryDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c corporationAllianceHistoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) *corporationAllianceHistoryDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c corporationAllianceHistoryDo) RightJoin(table schema.Tabler, on ...field.Expr) *corporationAllianceHistoryDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c corporationAllianceHistoryDo) Group(cols ...field.Expr) *corporationAllianceHistoryDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c corporationAllianceHistoryDo) Having(conds ...gen.Condition) *corporationAllianceHistoryDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c corporationAllianceHistoryDo) Limit(limit int) *corporationAllianceHistoryDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c corporationAllianceHistoryDo) Offset(offset int) *corporationAllianceHistoryDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c corporationAllianceHistoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *corporationAllianceHistoryDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c corporationAllianceHistoryDo) Unscoped() *corporationAllianceHistoryDo {
	return c.withDO(c.DO.Unscoped())
}

func (c corporationAllianceHistoryDo) Create(values ...*model.CorporationAllianceHistory) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c corporationAllianceHistoryDo) CreateInBatches(values []*model.CorporationAllianceHistory, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c corporationAllianceHistoryDo) Save(values ...*model.CorporationAllianceHistory) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c corporationAllianceHistoryDo) First() (*model.CorporationAllianceHistory, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CorporationAllianceHistory), nil
	}
}

func (c corporationAllianceHistoryDo) Take() (*model.CorporationAllianceHistory, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CorporationAllianceHistory), nil
	}
}

func (c corporationAllianceHistoryDo) Last() (*model.CorporationAllianceHistory, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CorporationAllianceHistory), nil
	}
}

func (c corporationAllianceHistoryDo) Find() ([]*model.CorporationAllianceHistory, error) {
	result, err := c.DO.Find()
	return result.([]*model.CorporationAllianceHistory), err
}

func (c corporationAllianceHistoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CorporationAllianceHistory, err error) {
	buf := make([]*model.CorporationAllianceHistory, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c corporationAllianceHistoryDo) FindInBatches(result *[]*model.CorporationAllianceHistory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c corporationAllianceHistoryDo) Attrs(attrs ...field.AssignExpr) *corporationAllianceHistoryDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c corporationAllianceHistoryDo) Assign(attrs ...field.AssignExpr) *corporationAllianceHistoryDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c corporationAllianceHistoryDo) Joins(fields ...field.RelationField) *corporationAllianceHistoryDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c corporationAllianceHistoryDo) Preload(fields ...field.RelationField) *corporationAllianceHistoryDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c corporationAllianceHistoryDo) FirstOrInit() (*model.CorporationAllianceHistory, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CorporationAllianceHistory), nil
	}
}

func (c corporationAllianceHistoryDo) FirstOrCreate() (*model.CorporationAllianceHistory, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CorporationAllianceHistory), nil
	}
}

func (c corporationAllianceHistoryDo) FindByPage(offset int, limit int) (result []*model.CorporationAllianceHistory, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c corporationAllianceHistoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c corporationAllianceHistoryDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c corporationAllianceHistoryDo) Delete(models ...*model.CorporationAllianceHistory) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *corporationAllianceHistoryDo) withDO(do gen.Dao) *corporationAllianceHistoryDo {
	c.DO = *do.(*gen.DO)
	return c
}
