// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package database

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/buckbrady/evebot-tools-backend/pkg/model"
)

func newCorporationIcon(db *gorm.DB, opts ...gen.DOOption) corporationIcon {
	_corporationIcon := corporationIcon{}

	_corporationIcon.corporationIconDo.UseDB(db, opts...)
	_corporationIcon.corporationIconDo.UseModel(&model.CorporationIcon{})

	tableName := _corporationIcon.corporationIconDo.TableName()
	_corporationIcon.ALL = field.NewAsterisk(tableName)
	_corporationIcon.ID = field.NewInt32(tableName, "id")
	_corporationIcon.Px128x128 = field.NewString(tableName, "px128x128")
	_corporationIcon.Px256x256 = field.NewString(tableName, "px256x256")
	_corporationIcon.Px64x64 = field.NewString(tableName, "px64x64")

	_corporationIcon.fillFieldMap()

	return _corporationIcon
}

type corporationIcon struct {
	corporationIconDo corporationIconDo

	ALL       field.Asterisk
	ID        field.Int32
	Px128x128 field.String
	Px256x256 field.String
	Px64x64   field.String

	fieldMap map[string]field.Expr
}

func (c corporationIcon) Table(newTableName string) *corporationIcon {
	c.corporationIconDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c corporationIcon) As(alias string) *corporationIcon {
	c.corporationIconDo.DO = *(c.corporationIconDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *corporationIcon) updateTableName(table string) *corporationIcon {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt32(table, "id")
	c.Px128x128 = field.NewString(table, "px128x128")
	c.Px256x256 = field.NewString(table, "px256x256")
	c.Px64x64 = field.NewString(table, "px64x64")

	c.fillFieldMap()

	return c
}

func (c *corporationIcon) WithContext(ctx context.Context) *corporationIconDo {
	return c.corporationIconDo.WithContext(ctx)
}

func (c corporationIcon) TableName() string { return c.corporationIconDo.TableName() }

func (c corporationIcon) Alias() string { return c.corporationIconDo.Alias() }

func (c corporationIcon) Columns(cols ...field.Expr) gen.Columns {
	return c.corporationIconDo.Columns(cols...)
}

func (c *corporationIcon) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *corporationIcon) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 4)
	c.fieldMap["id"] = c.ID
	c.fieldMap["px128x128"] = c.Px128x128
	c.fieldMap["px256x256"] = c.Px256x256
	c.fieldMap["px64x64"] = c.Px64x64
}

func (c corporationIcon) clone(db *gorm.DB) corporationIcon {
	c.corporationIconDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c corporationIcon) replaceDB(db *gorm.DB) corporationIcon {
	c.corporationIconDo.ReplaceDB(db)
	return c
}

type corporationIconDo struct{ gen.DO }

func (c corporationIconDo) Debug() *corporationIconDo {
	return c.withDO(c.DO.Debug())
}

func (c corporationIconDo) WithContext(ctx context.Context) *corporationIconDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c corporationIconDo) ReadDB() *corporationIconDo {
	return c.Clauses(dbresolver.Read)
}

func (c corporationIconDo) WriteDB() *corporationIconDo {
	return c.Clauses(dbresolver.Write)
}

func (c corporationIconDo) Session(config *gorm.Session) *corporationIconDo {
	return c.withDO(c.DO.Session(config))
}

func (c corporationIconDo) Clauses(conds ...clause.Expression) *corporationIconDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c corporationIconDo) Returning(value interface{}, columns ...string) *corporationIconDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c corporationIconDo) Not(conds ...gen.Condition) *corporationIconDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c corporationIconDo) Or(conds ...gen.Condition) *corporationIconDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c corporationIconDo) Select(conds ...field.Expr) *corporationIconDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c corporationIconDo) Where(conds ...gen.Condition) *corporationIconDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c corporationIconDo) Order(conds ...field.Expr) *corporationIconDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c corporationIconDo) Distinct(cols ...field.Expr) *corporationIconDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c corporationIconDo) Omit(cols ...field.Expr) *corporationIconDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c corporationIconDo) Join(table schema.Tabler, on ...field.Expr) *corporationIconDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c corporationIconDo) LeftJoin(table schema.Tabler, on ...field.Expr) *corporationIconDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c corporationIconDo) RightJoin(table schema.Tabler, on ...field.Expr) *corporationIconDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c corporationIconDo) Group(cols ...field.Expr) *corporationIconDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c corporationIconDo) Having(conds ...gen.Condition) *corporationIconDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c corporationIconDo) Limit(limit int) *corporationIconDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c corporationIconDo) Offset(offset int) *corporationIconDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c corporationIconDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *corporationIconDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c corporationIconDo) Unscoped() *corporationIconDo {
	return c.withDO(c.DO.Unscoped())
}

func (c corporationIconDo) Create(values ...*model.CorporationIcon) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c corporationIconDo) CreateInBatches(values []*model.CorporationIcon, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c corporationIconDo) Save(values ...*model.CorporationIcon) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c corporationIconDo) First() (*model.CorporationIcon, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CorporationIcon), nil
	}
}

func (c corporationIconDo) Take() (*model.CorporationIcon, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CorporationIcon), nil
	}
}

func (c corporationIconDo) Last() (*model.CorporationIcon, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CorporationIcon), nil
	}
}

func (c corporationIconDo) Find() ([]*model.CorporationIcon, error) {
	result, err := c.DO.Find()
	return result.([]*model.CorporationIcon), err
}

func (c corporationIconDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CorporationIcon, err error) {
	buf := make([]*model.CorporationIcon, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c corporationIconDo) FindInBatches(result *[]*model.CorporationIcon, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c corporationIconDo) Attrs(attrs ...field.AssignExpr) *corporationIconDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c corporationIconDo) Assign(attrs ...field.AssignExpr) *corporationIconDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c corporationIconDo) Joins(fields ...field.RelationField) *corporationIconDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c corporationIconDo) Preload(fields ...field.RelationField) *corporationIconDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c corporationIconDo) FirstOrInit() (*model.CorporationIcon, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CorporationIcon), nil
	}
}

func (c corporationIconDo) FirstOrCreate() (*model.CorporationIcon, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CorporationIcon), nil
	}
}

func (c corporationIconDo) FindByPage(offset int, limit int) (result []*model.CorporationIcon, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c corporationIconDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c corporationIconDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c corporationIconDo) Delete(models ...*model.CorporationIcon) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *corporationIconDo) withDO(do gen.Dao) *corporationIconDo {
	c.DO = *do.(*gen.DO)
	return c
}
