// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package database

import (
	"context"
	"fmt"
	"testing"

	"github.com/buckbrady/evebot-tools-backend/pkg/model"
	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
)

func init() {
	InitializeDB()
	err := db.AutoMigrate(&model.KillmailStat{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&model.KillmailStat{}) fail: %s", err)
	}
}

func Test_killmailStatQuery(t *testing.T) {
	killmailStat := newKillmailStat(db)
	killmailStat = *killmailStat.As(killmailStat.TableName())
	_do := killmailStat.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(killmailStat.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <killmail_stats> fail:", err)
		return
	}

	_, ok := killmailStat.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from killmailStat success")
	}

	err = _do.Create(&model.KillmailStat{})
	if err != nil {
		t.Error("create item in table <killmail_stats> fail:", err)
	}

	err = _do.Save(&model.KillmailStat{})
	if err != nil {
		t.Error("create item in table <killmail_stats> fail:", err)
	}

	err = _do.CreateInBatches([]*model.KillmailStat{{}, {}}, 10)
	if err != nil {
		t.Error("create item in table <killmail_stats> fail:", err)
	}

	_, err = _do.Select(killmailStat.ALL).Take()
	if err != nil {
		t.Error("Take() on table <killmail_stats> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <killmail_stats> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <killmail_stats> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <killmail_stats> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*model.KillmailStat{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <killmail_stats> fail:", err)
	}

	_, err = _do.Select(killmailStat.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <killmail_stats> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <killmail_stats> fail:", err)
	}

	_, err = _do.Select(killmailStat.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <killmail_stats> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <killmail_stats> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <killmail_stats> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <killmail_stats> fail:", err)
	}

	_, err = _do.ScanByPage(&model.KillmailStat{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <killmail_stats> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <killmail_stats> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <killmail_stats> fail:", err)
	}

	var _a _another
	var _aPK = field.NewString(_a.TableName(), "id")

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <killmail_stats> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <killmail_stats> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <killmail_stats> fail:", err)
	}
}
