// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package database

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/buckbrady/evebot-tools-backend/pkg/model"
)

func newKillmailVictim(db *gorm.DB, opts ...gen.DOOption) killmailVictim {
	_killmailVictim := killmailVictim{}

	_killmailVictim.killmailVictimDo.UseDB(db, opts...)
	_killmailVictim.killmailVictimDo.UseModel(&model.KillmailVictim{})

	tableName := _killmailVictim.killmailVictimDo.TableName()
	_killmailVictim.ALL = field.NewAsterisk(tableName)
	_killmailVictim.ID = field.NewInt64(tableName, "id")
	_killmailVictim.CharacterID = field.NewInt32(tableName, "character_id")
	_killmailVictim.CorporationID = field.NewInt32(tableName, "corporation_id")
	_killmailVictim.AllianceID = field.NewInt32(tableName, "alliance_id")
	_killmailVictim.FactionID = field.NewInt32(tableName, "faction_id")

	_killmailVictim.fillFieldMap()

	return _killmailVictim
}

type killmailVictim struct {
	killmailVictimDo killmailVictimDo

	ALL           field.Asterisk
	ID            field.Int64
	CharacterID   field.Int32
	CorporationID field.Int32
	AllianceID    field.Int32
	FactionID     field.Int32

	fieldMap map[string]field.Expr
}

func (k killmailVictim) Table(newTableName string) *killmailVictim {
	k.killmailVictimDo.UseTable(newTableName)
	return k.updateTableName(newTableName)
}

func (k killmailVictim) As(alias string) *killmailVictim {
	k.killmailVictimDo.DO = *(k.killmailVictimDo.As(alias).(*gen.DO))
	return k.updateTableName(alias)
}

func (k *killmailVictim) updateTableName(table string) *killmailVictim {
	k.ALL = field.NewAsterisk(table)
	k.ID = field.NewInt64(table, "id")
	k.CharacterID = field.NewInt32(table, "character_id")
	k.CorporationID = field.NewInt32(table, "corporation_id")
	k.AllianceID = field.NewInt32(table, "alliance_id")
	k.FactionID = field.NewInt32(table, "faction_id")

	k.fillFieldMap()

	return k
}

func (k *killmailVictim) WithContext(ctx context.Context) *killmailVictimDo {
	return k.killmailVictimDo.WithContext(ctx)
}

func (k killmailVictim) TableName() string { return k.killmailVictimDo.TableName() }

func (k killmailVictim) Alias() string { return k.killmailVictimDo.Alias() }

func (k killmailVictim) Columns(cols ...field.Expr) gen.Columns {
	return k.killmailVictimDo.Columns(cols...)
}

func (k *killmailVictim) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := k.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (k *killmailVictim) fillFieldMap() {
	k.fieldMap = make(map[string]field.Expr, 5)
	k.fieldMap["id"] = k.ID
	k.fieldMap["character_id"] = k.CharacterID
	k.fieldMap["corporation_id"] = k.CorporationID
	k.fieldMap["alliance_id"] = k.AllianceID
	k.fieldMap["faction_id"] = k.FactionID
}

func (k killmailVictim) clone(db *gorm.DB) killmailVictim {
	k.killmailVictimDo.ReplaceConnPool(db.Statement.ConnPool)
	return k
}

func (k killmailVictim) replaceDB(db *gorm.DB) killmailVictim {
	k.killmailVictimDo.ReplaceDB(db)
	return k
}

type killmailVictimDo struct{ gen.DO }

func (k killmailVictimDo) Debug() *killmailVictimDo {
	return k.withDO(k.DO.Debug())
}

func (k killmailVictimDo) WithContext(ctx context.Context) *killmailVictimDo {
	return k.withDO(k.DO.WithContext(ctx))
}

func (k killmailVictimDo) ReadDB() *killmailVictimDo {
	return k.Clauses(dbresolver.Read)
}

func (k killmailVictimDo) WriteDB() *killmailVictimDo {
	return k.Clauses(dbresolver.Write)
}

func (k killmailVictimDo) Session(config *gorm.Session) *killmailVictimDo {
	return k.withDO(k.DO.Session(config))
}

func (k killmailVictimDo) Clauses(conds ...clause.Expression) *killmailVictimDo {
	return k.withDO(k.DO.Clauses(conds...))
}

func (k killmailVictimDo) Returning(value interface{}, columns ...string) *killmailVictimDo {
	return k.withDO(k.DO.Returning(value, columns...))
}

func (k killmailVictimDo) Not(conds ...gen.Condition) *killmailVictimDo {
	return k.withDO(k.DO.Not(conds...))
}

func (k killmailVictimDo) Or(conds ...gen.Condition) *killmailVictimDo {
	return k.withDO(k.DO.Or(conds...))
}

func (k killmailVictimDo) Select(conds ...field.Expr) *killmailVictimDo {
	return k.withDO(k.DO.Select(conds...))
}

func (k killmailVictimDo) Where(conds ...gen.Condition) *killmailVictimDo {
	return k.withDO(k.DO.Where(conds...))
}

func (k killmailVictimDo) Order(conds ...field.Expr) *killmailVictimDo {
	return k.withDO(k.DO.Order(conds...))
}

func (k killmailVictimDo) Distinct(cols ...field.Expr) *killmailVictimDo {
	return k.withDO(k.DO.Distinct(cols...))
}

func (k killmailVictimDo) Omit(cols ...field.Expr) *killmailVictimDo {
	return k.withDO(k.DO.Omit(cols...))
}

func (k killmailVictimDo) Join(table schema.Tabler, on ...field.Expr) *killmailVictimDo {
	return k.withDO(k.DO.Join(table, on...))
}

func (k killmailVictimDo) LeftJoin(table schema.Tabler, on ...field.Expr) *killmailVictimDo {
	return k.withDO(k.DO.LeftJoin(table, on...))
}

func (k killmailVictimDo) RightJoin(table schema.Tabler, on ...field.Expr) *killmailVictimDo {
	return k.withDO(k.DO.RightJoin(table, on...))
}

func (k killmailVictimDo) Group(cols ...field.Expr) *killmailVictimDo {
	return k.withDO(k.DO.Group(cols...))
}

func (k killmailVictimDo) Having(conds ...gen.Condition) *killmailVictimDo {
	return k.withDO(k.DO.Having(conds...))
}

func (k killmailVictimDo) Limit(limit int) *killmailVictimDo {
	return k.withDO(k.DO.Limit(limit))
}

func (k killmailVictimDo) Offset(offset int) *killmailVictimDo {
	return k.withDO(k.DO.Offset(offset))
}

func (k killmailVictimDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *killmailVictimDo {
	return k.withDO(k.DO.Scopes(funcs...))
}

func (k killmailVictimDo) Unscoped() *killmailVictimDo {
	return k.withDO(k.DO.Unscoped())
}

func (k killmailVictimDo) Create(values ...*model.KillmailVictim) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Create(values)
}

func (k killmailVictimDo) CreateInBatches(values []*model.KillmailVictim, batchSize int) error {
	return k.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (k killmailVictimDo) Save(values ...*model.KillmailVictim) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Save(values)
}

func (k killmailVictimDo) First() (*model.KillmailVictim, error) {
	if result, err := k.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.KillmailVictim), nil
	}
}

func (k killmailVictimDo) Take() (*model.KillmailVictim, error) {
	if result, err := k.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.KillmailVictim), nil
	}
}

func (k killmailVictimDo) Last() (*model.KillmailVictim, error) {
	if result, err := k.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.KillmailVictim), nil
	}
}

func (k killmailVictimDo) Find() ([]*model.KillmailVictim, error) {
	result, err := k.DO.Find()
	return result.([]*model.KillmailVictim), err
}

func (k killmailVictimDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.KillmailVictim, err error) {
	buf := make([]*model.KillmailVictim, 0, batchSize)
	err = k.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (k killmailVictimDo) FindInBatches(result *[]*model.KillmailVictim, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return k.DO.FindInBatches(result, batchSize, fc)
}

func (k killmailVictimDo) Attrs(attrs ...field.AssignExpr) *killmailVictimDo {
	return k.withDO(k.DO.Attrs(attrs...))
}

func (k killmailVictimDo) Assign(attrs ...field.AssignExpr) *killmailVictimDo {
	return k.withDO(k.DO.Assign(attrs...))
}

func (k killmailVictimDo) Joins(fields ...field.RelationField) *killmailVictimDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Joins(_f))
	}
	return &k
}

func (k killmailVictimDo) Preload(fields ...field.RelationField) *killmailVictimDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Preload(_f))
	}
	return &k
}

func (k killmailVictimDo) FirstOrInit() (*model.KillmailVictim, error) {
	if result, err := k.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.KillmailVictim), nil
	}
}

func (k killmailVictimDo) FirstOrCreate() (*model.KillmailVictim, error) {
	if result, err := k.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.KillmailVictim), nil
	}
}

func (k killmailVictimDo) FindByPage(offset int, limit int) (result []*model.KillmailVictim, count int64, err error) {
	result, err = k.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = k.Offset(-1).Limit(-1).Count()
	return
}

func (k killmailVictimDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = k.Count()
	if err != nil {
		return
	}

	err = k.Offset(offset).Limit(limit).Scan(result)
	return
}

func (k killmailVictimDo) Scan(result interface{}) (err error) {
	return k.DO.Scan(result)
}

func (k killmailVictimDo) Delete(models ...*model.KillmailVictim) (result gen.ResultInfo, err error) {
	return k.DO.Delete(models)
}

func (k *killmailVictimDo) withDO(do gen.Dao) *killmailVictimDo {
	k.DO = *do.(*gen.DO)
	return k
}
