// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package database

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/buckbrady/evebot-tools-backend/pkg/model"
)

func newUniversePlanet(db *gorm.DB, opts ...gen.DOOption) universePlanet {
	_universePlanet := universePlanet{}

	_universePlanet.universePlanetDo.UseDB(db, opts...)
	_universePlanet.universePlanetDo.UseModel(&model.UniversePlanet{})

	tableName := _universePlanet.universePlanetDo.TableName()
	_universePlanet.ALL = field.NewAsterisk(tableName)
	_universePlanet.ID = field.NewInt32(tableName, "id")
	_universePlanet.SystemID = field.NewInt32(tableName, "system_id")
	_universePlanet.Name = field.NewString(tableName, "name")
	_universePlanet.PositionX = field.NewFloat64(tableName, "position_x")
	_universePlanet.PositionY = field.NewFloat64(tableName, "position_y")
	_universePlanet.PositionZ = field.NewFloat64(tableName, "position_z")
	_universePlanet.TypeID = field.NewInt32(tableName, "type_id")

	_universePlanet.fillFieldMap()

	return _universePlanet
}

type universePlanet struct {
	universePlanetDo universePlanetDo

	ALL       field.Asterisk
	ID        field.Int32
	SystemID  field.Int32
	Name      field.String
	PositionX field.Float64
	PositionY field.Float64
	PositionZ field.Float64
	TypeID    field.Int32

	fieldMap map[string]field.Expr
}

func (u universePlanet) Table(newTableName string) *universePlanet {
	u.universePlanetDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u universePlanet) As(alias string) *universePlanet {
	u.universePlanetDo.DO = *(u.universePlanetDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *universePlanet) updateTableName(table string) *universePlanet {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewInt32(table, "id")
	u.SystemID = field.NewInt32(table, "system_id")
	u.Name = field.NewString(table, "name")
	u.PositionX = field.NewFloat64(table, "position_x")
	u.PositionY = field.NewFloat64(table, "position_y")
	u.PositionZ = field.NewFloat64(table, "position_z")
	u.TypeID = field.NewInt32(table, "type_id")

	u.fillFieldMap()

	return u
}

func (u *universePlanet) WithContext(ctx context.Context) *universePlanetDo {
	return u.universePlanetDo.WithContext(ctx)
}

func (u universePlanet) TableName() string { return u.universePlanetDo.TableName() }

func (u universePlanet) Alias() string { return u.universePlanetDo.Alias() }

func (u universePlanet) Columns(cols ...field.Expr) gen.Columns {
	return u.universePlanetDo.Columns(cols...)
}

func (u *universePlanet) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *universePlanet) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 7)
	u.fieldMap["id"] = u.ID
	u.fieldMap["system_id"] = u.SystemID
	u.fieldMap["name"] = u.Name
	u.fieldMap["position_x"] = u.PositionX
	u.fieldMap["position_y"] = u.PositionY
	u.fieldMap["position_z"] = u.PositionZ
	u.fieldMap["type_id"] = u.TypeID
}

func (u universePlanet) clone(db *gorm.DB) universePlanet {
	u.universePlanetDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u universePlanet) replaceDB(db *gorm.DB) universePlanet {
	u.universePlanetDo.ReplaceDB(db)
	return u
}

type universePlanetDo struct{ gen.DO }

func (u universePlanetDo) Debug() *universePlanetDo {
	return u.withDO(u.DO.Debug())
}

func (u universePlanetDo) WithContext(ctx context.Context) *universePlanetDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u universePlanetDo) ReadDB() *universePlanetDo {
	return u.Clauses(dbresolver.Read)
}

func (u universePlanetDo) WriteDB() *universePlanetDo {
	return u.Clauses(dbresolver.Write)
}

func (u universePlanetDo) Session(config *gorm.Session) *universePlanetDo {
	return u.withDO(u.DO.Session(config))
}

func (u universePlanetDo) Clauses(conds ...clause.Expression) *universePlanetDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u universePlanetDo) Returning(value interface{}, columns ...string) *universePlanetDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u universePlanetDo) Not(conds ...gen.Condition) *universePlanetDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u universePlanetDo) Or(conds ...gen.Condition) *universePlanetDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u universePlanetDo) Select(conds ...field.Expr) *universePlanetDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u universePlanetDo) Where(conds ...gen.Condition) *universePlanetDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u universePlanetDo) Order(conds ...field.Expr) *universePlanetDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u universePlanetDo) Distinct(cols ...field.Expr) *universePlanetDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u universePlanetDo) Omit(cols ...field.Expr) *universePlanetDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u universePlanetDo) Join(table schema.Tabler, on ...field.Expr) *universePlanetDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u universePlanetDo) LeftJoin(table schema.Tabler, on ...field.Expr) *universePlanetDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u universePlanetDo) RightJoin(table schema.Tabler, on ...field.Expr) *universePlanetDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u universePlanetDo) Group(cols ...field.Expr) *universePlanetDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u universePlanetDo) Having(conds ...gen.Condition) *universePlanetDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u universePlanetDo) Limit(limit int) *universePlanetDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u universePlanetDo) Offset(offset int) *universePlanetDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u universePlanetDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *universePlanetDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u universePlanetDo) Unscoped() *universePlanetDo {
	return u.withDO(u.DO.Unscoped())
}

func (u universePlanetDo) Create(values ...*model.UniversePlanet) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u universePlanetDo) CreateInBatches(values []*model.UniversePlanet, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u universePlanetDo) Save(values ...*model.UniversePlanet) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u universePlanetDo) First() (*model.UniversePlanet, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UniversePlanet), nil
	}
}

func (u universePlanetDo) Take() (*model.UniversePlanet, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UniversePlanet), nil
	}
}

func (u universePlanetDo) Last() (*model.UniversePlanet, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UniversePlanet), nil
	}
}

func (u universePlanetDo) Find() ([]*model.UniversePlanet, error) {
	result, err := u.DO.Find()
	return result.([]*model.UniversePlanet), err
}

func (u universePlanetDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UniversePlanet, err error) {
	buf := make([]*model.UniversePlanet, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u universePlanetDo) FindInBatches(result *[]*model.UniversePlanet, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u universePlanetDo) Attrs(attrs ...field.AssignExpr) *universePlanetDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u universePlanetDo) Assign(attrs ...field.AssignExpr) *universePlanetDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u universePlanetDo) Joins(fields ...field.RelationField) *universePlanetDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u universePlanetDo) Preload(fields ...field.RelationField) *universePlanetDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u universePlanetDo) FirstOrInit() (*model.UniversePlanet, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UniversePlanet), nil
	}
}

func (u universePlanetDo) FirstOrCreate() (*model.UniversePlanet, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UniversePlanet), nil
	}
}

func (u universePlanetDo) FindByPage(offset int, limit int) (result []*model.UniversePlanet, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u universePlanetDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u universePlanetDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u universePlanetDo) Delete(models ...*model.UniversePlanet) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *universePlanetDo) withDO(do gen.Dao) *universePlanetDo {
	u.DO = *do.(*gen.DO)
	return u
}
