// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package database

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/buckbrady/evebot-tools-backend/pkg/model"
)

func newUniverseCategory(db *gorm.DB, opts ...gen.DOOption) universeCategory {
	_universeCategory := universeCategory{}

	_universeCategory.universeCategoryDo.UseDB(db, opts...)
	_universeCategory.universeCategoryDo.UseModel(&model.UniverseCategory{})

	tableName := _universeCategory.universeCategoryDo.TableName()
	_universeCategory.ALL = field.NewAsterisk(tableName)
	_universeCategory.ID = field.NewInt32(tableName, "id")
	_universeCategory.Name = field.NewString(tableName, "name")
	_universeCategory.Published = field.NewBool(tableName, "published")

	_universeCategory.fillFieldMap()

	return _universeCategory
}

type universeCategory struct {
	universeCategoryDo universeCategoryDo

	ALL       field.Asterisk
	ID        field.Int32
	Name      field.String
	Published field.Bool

	fieldMap map[string]field.Expr
}

func (u universeCategory) Table(newTableName string) *universeCategory {
	u.universeCategoryDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u universeCategory) As(alias string) *universeCategory {
	u.universeCategoryDo.DO = *(u.universeCategoryDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *universeCategory) updateTableName(table string) *universeCategory {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewInt32(table, "id")
	u.Name = field.NewString(table, "name")
	u.Published = field.NewBool(table, "published")

	u.fillFieldMap()

	return u
}

func (u *universeCategory) WithContext(ctx context.Context) *universeCategoryDo {
	return u.universeCategoryDo.WithContext(ctx)
}

func (u universeCategory) TableName() string { return u.universeCategoryDo.TableName() }

func (u universeCategory) Alias() string { return u.universeCategoryDo.Alias() }

func (u universeCategory) Columns(cols ...field.Expr) gen.Columns {
	return u.universeCategoryDo.Columns(cols...)
}

func (u *universeCategory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *universeCategory) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 3)
	u.fieldMap["id"] = u.ID
	u.fieldMap["name"] = u.Name
	u.fieldMap["published"] = u.Published
}

func (u universeCategory) clone(db *gorm.DB) universeCategory {
	u.universeCategoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u universeCategory) replaceDB(db *gorm.DB) universeCategory {
	u.universeCategoryDo.ReplaceDB(db)
	return u
}

type universeCategoryDo struct{ gen.DO }

func (u universeCategoryDo) Debug() *universeCategoryDo {
	return u.withDO(u.DO.Debug())
}

func (u universeCategoryDo) WithContext(ctx context.Context) *universeCategoryDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u universeCategoryDo) ReadDB() *universeCategoryDo {
	return u.Clauses(dbresolver.Read)
}

func (u universeCategoryDo) WriteDB() *universeCategoryDo {
	return u.Clauses(dbresolver.Write)
}

func (u universeCategoryDo) Session(config *gorm.Session) *universeCategoryDo {
	return u.withDO(u.DO.Session(config))
}

func (u universeCategoryDo) Clauses(conds ...clause.Expression) *universeCategoryDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u universeCategoryDo) Returning(value interface{}, columns ...string) *universeCategoryDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u universeCategoryDo) Not(conds ...gen.Condition) *universeCategoryDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u universeCategoryDo) Or(conds ...gen.Condition) *universeCategoryDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u universeCategoryDo) Select(conds ...field.Expr) *universeCategoryDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u universeCategoryDo) Where(conds ...gen.Condition) *universeCategoryDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u universeCategoryDo) Order(conds ...field.Expr) *universeCategoryDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u universeCategoryDo) Distinct(cols ...field.Expr) *universeCategoryDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u universeCategoryDo) Omit(cols ...field.Expr) *universeCategoryDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u universeCategoryDo) Join(table schema.Tabler, on ...field.Expr) *universeCategoryDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u universeCategoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) *universeCategoryDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u universeCategoryDo) RightJoin(table schema.Tabler, on ...field.Expr) *universeCategoryDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u universeCategoryDo) Group(cols ...field.Expr) *universeCategoryDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u universeCategoryDo) Having(conds ...gen.Condition) *universeCategoryDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u universeCategoryDo) Limit(limit int) *universeCategoryDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u universeCategoryDo) Offset(offset int) *universeCategoryDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u universeCategoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *universeCategoryDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u universeCategoryDo) Unscoped() *universeCategoryDo {
	return u.withDO(u.DO.Unscoped())
}

func (u universeCategoryDo) Create(values ...*model.UniverseCategory) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u universeCategoryDo) CreateInBatches(values []*model.UniverseCategory, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u universeCategoryDo) Save(values ...*model.UniverseCategory) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u universeCategoryDo) First() (*model.UniverseCategory, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UniverseCategory), nil
	}
}

func (u universeCategoryDo) Take() (*model.UniverseCategory, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UniverseCategory), nil
	}
}

func (u universeCategoryDo) Last() (*model.UniverseCategory, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UniverseCategory), nil
	}
}

func (u universeCategoryDo) Find() ([]*model.UniverseCategory, error) {
	result, err := u.DO.Find()
	return result.([]*model.UniverseCategory), err
}

func (u universeCategoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UniverseCategory, err error) {
	buf := make([]*model.UniverseCategory, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u universeCategoryDo) FindInBatches(result *[]*model.UniverseCategory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u universeCategoryDo) Attrs(attrs ...field.AssignExpr) *universeCategoryDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u universeCategoryDo) Assign(attrs ...field.AssignExpr) *universeCategoryDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u universeCategoryDo) Joins(fields ...field.RelationField) *universeCategoryDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u universeCategoryDo) Preload(fields ...field.RelationField) *universeCategoryDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u universeCategoryDo) FirstOrInit() (*model.UniverseCategory, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UniverseCategory), nil
	}
}

func (u universeCategoryDo) FirstOrCreate() (*model.UniverseCategory, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UniverseCategory), nil
	}
}

func (u universeCategoryDo) FindByPage(offset int, limit int) (result []*model.UniverseCategory, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u universeCategoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u universeCategoryDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u universeCategoryDo) Delete(models ...*model.UniverseCategory) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *universeCategoryDo) withDO(do gen.Dao) *universeCategoryDo {
	u.DO = *do.(*gen.DO)
	return u
}
