// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package database

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/buckbrady/evebot-tools-backend/pkg/model"
)

func newUniverseSystemKill(db *gorm.DB, opts ...gen.DOOption) universeSystemKill {
	_universeSystemKill := universeSystemKill{}

	_universeSystemKill.universeSystemKillDo.UseDB(db, opts...)
	_universeSystemKill.universeSystemKillDo.UseModel(&model.UniverseSystemKill{})

	tableName := _universeSystemKill.universeSystemKillDo.TableName()
	_universeSystemKill.ALL = field.NewAsterisk(tableName)
	_universeSystemKill.SystemID = field.NewInt32(tableName, "system_id")
	_universeSystemKill.Timestamp = field.NewTime(tableName, "timestamp")
	_universeSystemKill.ShipKills = field.NewInt32(tableName, "ship_kills")
	_universeSystemKill.PodKills = field.NewInt32(tableName, "pod_kills")
	_universeSystemKill.NpcKills = field.NewInt32(tableName, "npc_kills")

	_universeSystemKill.fillFieldMap()

	return _universeSystemKill
}

type universeSystemKill struct {
	universeSystemKillDo universeSystemKillDo

	ALL       field.Asterisk
	SystemID  field.Int32
	Timestamp field.Time
	ShipKills field.Int32
	PodKills  field.Int32
	NpcKills  field.Int32

	fieldMap map[string]field.Expr
}

func (u universeSystemKill) Table(newTableName string) *universeSystemKill {
	u.universeSystemKillDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u universeSystemKill) As(alias string) *universeSystemKill {
	u.universeSystemKillDo.DO = *(u.universeSystemKillDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *universeSystemKill) updateTableName(table string) *universeSystemKill {
	u.ALL = field.NewAsterisk(table)
	u.SystemID = field.NewInt32(table, "system_id")
	u.Timestamp = field.NewTime(table, "timestamp")
	u.ShipKills = field.NewInt32(table, "ship_kills")
	u.PodKills = field.NewInt32(table, "pod_kills")
	u.NpcKills = field.NewInt32(table, "npc_kills")

	u.fillFieldMap()

	return u
}

func (u *universeSystemKill) WithContext(ctx context.Context) *universeSystemKillDo {
	return u.universeSystemKillDo.WithContext(ctx)
}

func (u universeSystemKill) TableName() string { return u.universeSystemKillDo.TableName() }

func (u universeSystemKill) Alias() string { return u.universeSystemKillDo.Alias() }

func (u universeSystemKill) Columns(cols ...field.Expr) gen.Columns {
	return u.universeSystemKillDo.Columns(cols...)
}

func (u *universeSystemKill) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *universeSystemKill) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 5)
	u.fieldMap["system_id"] = u.SystemID
	u.fieldMap["timestamp"] = u.Timestamp
	u.fieldMap["ship_kills"] = u.ShipKills
	u.fieldMap["pod_kills"] = u.PodKills
	u.fieldMap["npc_kills"] = u.NpcKills
}

func (u universeSystemKill) clone(db *gorm.DB) universeSystemKill {
	u.universeSystemKillDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u universeSystemKill) replaceDB(db *gorm.DB) universeSystemKill {
	u.universeSystemKillDo.ReplaceDB(db)
	return u
}

type universeSystemKillDo struct{ gen.DO }

func (u universeSystemKillDo) Debug() *universeSystemKillDo {
	return u.withDO(u.DO.Debug())
}

func (u universeSystemKillDo) WithContext(ctx context.Context) *universeSystemKillDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u universeSystemKillDo) ReadDB() *universeSystemKillDo {
	return u.Clauses(dbresolver.Read)
}

func (u universeSystemKillDo) WriteDB() *universeSystemKillDo {
	return u.Clauses(dbresolver.Write)
}

func (u universeSystemKillDo) Session(config *gorm.Session) *universeSystemKillDo {
	return u.withDO(u.DO.Session(config))
}

func (u universeSystemKillDo) Clauses(conds ...clause.Expression) *universeSystemKillDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u universeSystemKillDo) Returning(value interface{}, columns ...string) *universeSystemKillDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u universeSystemKillDo) Not(conds ...gen.Condition) *universeSystemKillDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u universeSystemKillDo) Or(conds ...gen.Condition) *universeSystemKillDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u universeSystemKillDo) Select(conds ...field.Expr) *universeSystemKillDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u universeSystemKillDo) Where(conds ...gen.Condition) *universeSystemKillDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u universeSystemKillDo) Order(conds ...field.Expr) *universeSystemKillDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u universeSystemKillDo) Distinct(cols ...field.Expr) *universeSystemKillDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u universeSystemKillDo) Omit(cols ...field.Expr) *universeSystemKillDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u universeSystemKillDo) Join(table schema.Tabler, on ...field.Expr) *universeSystemKillDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u universeSystemKillDo) LeftJoin(table schema.Tabler, on ...field.Expr) *universeSystemKillDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u universeSystemKillDo) RightJoin(table schema.Tabler, on ...field.Expr) *universeSystemKillDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u universeSystemKillDo) Group(cols ...field.Expr) *universeSystemKillDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u universeSystemKillDo) Having(conds ...gen.Condition) *universeSystemKillDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u universeSystemKillDo) Limit(limit int) *universeSystemKillDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u universeSystemKillDo) Offset(offset int) *universeSystemKillDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u universeSystemKillDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *universeSystemKillDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u universeSystemKillDo) Unscoped() *universeSystemKillDo {
	return u.withDO(u.DO.Unscoped())
}

func (u universeSystemKillDo) Create(values ...*model.UniverseSystemKill) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u universeSystemKillDo) CreateInBatches(values []*model.UniverseSystemKill, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u universeSystemKillDo) Save(values ...*model.UniverseSystemKill) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u universeSystemKillDo) First() (*model.UniverseSystemKill, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UniverseSystemKill), nil
	}
}

func (u universeSystemKillDo) Take() (*model.UniverseSystemKill, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UniverseSystemKill), nil
	}
}

func (u universeSystemKillDo) Last() (*model.UniverseSystemKill, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UniverseSystemKill), nil
	}
}

func (u universeSystemKillDo) Find() ([]*model.UniverseSystemKill, error) {
	result, err := u.DO.Find()
	return result.([]*model.UniverseSystemKill), err
}

func (u universeSystemKillDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UniverseSystemKill, err error) {
	buf := make([]*model.UniverseSystemKill, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u universeSystemKillDo) FindInBatches(result *[]*model.UniverseSystemKill, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u universeSystemKillDo) Attrs(attrs ...field.AssignExpr) *universeSystemKillDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u universeSystemKillDo) Assign(attrs ...field.AssignExpr) *universeSystemKillDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u universeSystemKillDo) Joins(fields ...field.RelationField) *universeSystemKillDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u universeSystemKillDo) Preload(fields ...field.RelationField) *universeSystemKillDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u universeSystemKillDo) FirstOrInit() (*model.UniverseSystemKill, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UniverseSystemKill), nil
	}
}

func (u universeSystemKillDo) FirstOrCreate() (*model.UniverseSystemKill, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UniverseSystemKill), nil
	}
}

func (u universeSystemKillDo) FindByPage(offset int, limit int) (result []*model.UniverseSystemKill, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u universeSystemKillDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u universeSystemKillDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u universeSystemKillDo) Delete(models ...*model.UniverseSystemKill) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *universeSystemKillDo) withDO(do gen.Dao) *universeSystemKillDo {
	u.DO = *do.(*gen.DO)
	return u
}
