// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package database

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/buckbrady/evebot-tools-backend/pkg/model"
)

func newUniverseGraphic(db *gorm.DB, opts ...gen.DOOption) universeGraphic {
	_universeGraphic := universeGraphic{}

	_universeGraphic.universeGraphicDo.UseDB(db, opts...)
	_universeGraphic.universeGraphicDo.UseModel(&model.UniverseGraphic{})

	tableName := _universeGraphic.universeGraphicDo.TableName()
	_universeGraphic.ALL = field.NewAsterisk(tableName)
	_universeGraphic.ID = field.NewInt32(tableName, "id")
	_universeGraphic.CollisionFile = field.NewString(tableName, "collision_file")
	_universeGraphic.GraphicFile = field.NewString(tableName, "graphic_file")
	_universeGraphic.IconFolder = field.NewString(tableName, "icon_folder")
	_universeGraphic.SofDna = field.NewString(tableName, "sof_dna")
	_universeGraphic.SofFationName = field.NewString(tableName, "sof_fation_name")
	_universeGraphic.SofHullName = field.NewString(tableName, "sof_hull_name")
	_universeGraphic.SofRaceName = field.NewString(tableName, "sof_race_name")

	_universeGraphic.fillFieldMap()

	return _universeGraphic
}

type universeGraphic struct {
	universeGraphicDo universeGraphicDo

	ALL           field.Asterisk
	ID            field.Int32
	CollisionFile field.String
	GraphicFile   field.String
	IconFolder    field.String
	SofDna        field.String
	SofFationName field.String
	SofHullName   field.String
	SofRaceName   field.String

	fieldMap map[string]field.Expr
}

func (u universeGraphic) Table(newTableName string) *universeGraphic {
	u.universeGraphicDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u universeGraphic) As(alias string) *universeGraphic {
	u.universeGraphicDo.DO = *(u.universeGraphicDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *universeGraphic) updateTableName(table string) *universeGraphic {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewInt32(table, "id")
	u.CollisionFile = field.NewString(table, "collision_file")
	u.GraphicFile = field.NewString(table, "graphic_file")
	u.IconFolder = field.NewString(table, "icon_folder")
	u.SofDna = field.NewString(table, "sof_dna")
	u.SofFationName = field.NewString(table, "sof_fation_name")
	u.SofHullName = field.NewString(table, "sof_hull_name")
	u.SofRaceName = field.NewString(table, "sof_race_name")

	u.fillFieldMap()

	return u
}

func (u *universeGraphic) WithContext(ctx context.Context) *universeGraphicDo {
	return u.universeGraphicDo.WithContext(ctx)
}

func (u universeGraphic) TableName() string { return u.universeGraphicDo.TableName() }

func (u universeGraphic) Alias() string { return u.universeGraphicDo.Alias() }

func (u universeGraphic) Columns(cols ...field.Expr) gen.Columns {
	return u.universeGraphicDo.Columns(cols...)
}

func (u *universeGraphic) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *universeGraphic) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 8)
	u.fieldMap["id"] = u.ID
	u.fieldMap["collision_file"] = u.CollisionFile
	u.fieldMap["graphic_file"] = u.GraphicFile
	u.fieldMap["icon_folder"] = u.IconFolder
	u.fieldMap["sof_dna"] = u.SofDna
	u.fieldMap["sof_fation_name"] = u.SofFationName
	u.fieldMap["sof_hull_name"] = u.SofHullName
	u.fieldMap["sof_race_name"] = u.SofRaceName
}

func (u universeGraphic) clone(db *gorm.DB) universeGraphic {
	u.universeGraphicDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u universeGraphic) replaceDB(db *gorm.DB) universeGraphic {
	u.universeGraphicDo.ReplaceDB(db)
	return u
}

type universeGraphicDo struct{ gen.DO }

func (u universeGraphicDo) Debug() *universeGraphicDo {
	return u.withDO(u.DO.Debug())
}

func (u universeGraphicDo) WithContext(ctx context.Context) *universeGraphicDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u universeGraphicDo) ReadDB() *universeGraphicDo {
	return u.Clauses(dbresolver.Read)
}

func (u universeGraphicDo) WriteDB() *universeGraphicDo {
	return u.Clauses(dbresolver.Write)
}

func (u universeGraphicDo) Session(config *gorm.Session) *universeGraphicDo {
	return u.withDO(u.DO.Session(config))
}

func (u universeGraphicDo) Clauses(conds ...clause.Expression) *universeGraphicDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u universeGraphicDo) Returning(value interface{}, columns ...string) *universeGraphicDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u universeGraphicDo) Not(conds ...gen.Condition) *universeGraphicDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u universeGraphicDo) Or(conds ...gen.Condition) *universeGraphicDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u universeGraphicDo) Select(conds ...field.Expr) *universeGraphicDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u universeGraphicDo) Where(conds ...gen.Condition) *universeGraphicDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u universeGraphicDo) Order(conds ...field.Expr) *universeGraphicDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u universeGraphicDo) Distinct(cols ...field.Expr) *universeGraphicDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u universeGraphicDo) Omit(cols ...field.Expr) *universeGraphicDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u universeGraphicDo) Join(table schema.Tabler, on ...field.Expr) *universeGraphicDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u universeGraphicDo) LeftJoin(table schema.Tabler, on ...field.Expr) *universeGraphicDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u universeGraphicDo) RightJoin(table schema.Tabler, on ...field.Expr) *universeGraphicDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u universeGraphicDo) Group(cols ...field.Expr) *universeGraphicDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u universeGraphicDo) Having(conds ...gen.Condition) *universeGraphicDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u universeGraphicDo) Limit(limit int) *universeGraphicDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u universeGraphicDo) Offset(offset int) *universeGraphicDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u universeGraphicDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *universeGraphicDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u universeGraphicDo) Unscoped() *universeGraphicDo {
	return u.withDO(u.DO.Unscoped())
}

func (u universeGraphicDo) Create(values ...*model.UniverseGraphic) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u universeGraphicDo) CreateInBatches(values []*model.UniverseGraphic, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u universeGraphicDo) Save(values ...*model.UniverseGraphic) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u universeGraphicDo) First() (*model.UniverseGraphic, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UniverseGraphic), nil
	}
}

func (u universeGraphicDo) Take() (*model.UniverseGraphic, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UniverseGraphic), nil
	}
}

func (u universeGraphicDo) Last() (*model.UniverseGraphic, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UniverseGraphic), nil
	}
}

func (u universeGraphicDo) Find() ([]*model.UniverseGraphic, error) {
	result, err := u.DO.Find()
	return result.([]*model.UniverseGraphic), err
}

func (u universeGraphicDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UniverseGraphic, err error) {
	buf := make([]*model.UniverseGraphic, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u universeGraphicDo) FindInBatches(result *[]*model.UniverseGraphic, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u universeGraphicDo) Attrs(attrs ...field.AssignExpr) *universeGraphicDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u universeGraphicDo) Assign(attrs ...field.AssignExpr) *universeGraphicDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u universeGraphicDo) Joins(fields ...field.RelationField) *universeGraphicDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u universeGraphicDo) Preload(fields ...field.RelationField) *universeGraphicDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u universeGraphicDo) FirstOrInit() (*model.UniverseGraphic, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UniverseGraphic), nil
	}
}

func (u universeGraphicDo) FirstOrCreate() (*model.UniverseGraphic, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UniverseGraphic), nil
	}
}

func (u universeGraphicDo) FindByPage(offset int, limit int) (result []*model.UniverseGraphic, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u universeGraphicDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u universeGraphicDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u universeGraphicDo) Delete(models ...*model.UniverseGraphic) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *universeGraphicDo) withDO(do gen.Dao) *universeGraphicDo {
	u.DO = *do.(*gen.DO)
	return u
}
