apiVersion: apps/v1
kind: Deployment
metadata:
  name: zkillsync
  labels:
    app: zkillsync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zkillsync
  template:
    metadata:
      name: zkillsync
      labels:
        app: zkillsync
    spec:
      containers:
        - name: zkillsync
          image: ghcr.io/buckbrady/evetools/zkillsync:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          env:
            - name: REDIS_ADDR
              value: redis-redis-ha-haproxy:6379
            - name: QUEUE_REDIS_DB
              value: "10"
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: evetools-secrets
                  key: SENTRY_ZKILLSYNC
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: evetools-secrets
                  key: MONGODB_URI
      restartPolicy: Always
