apiVersion: apps/v1
kind: Deployment
metadata:
  name: asynqmon
  labels:
    app: asynqmon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asynqmon
  template:
    metadata:
      name: asynqmon
      labels:
        app: asynqmon
    spec:
      containers:
        - name: asynqmon
          image: hibiken/asynqmon:0.7.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: REDIS_ADDR
              value: redis-redis-ha-haproxy:6379
            - name: REDIS_DB
              value: "10"
            - name: ENABLE_METRICS_EXPORTER
              value: "true"
            - name: PROMETHEUS_ADDR
              value: "http://192.168.0.2:9090"
      restartPolicy: Always
