apiVersion: v1
kind: Service
metadata:
  name: asynqmon
  labels:
    app: asynqmon
spec:
  selector:
    app: asynqmon
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP