apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: asynqmon
  namespace: evebot
spec:
  endpoints:
    - interval: 10s
#      targetPort: 8080
#      path: /metrics
  namespaceSelector:
    matchNames:
      - evebot
  selector:
    matchLabels:
      app: asynqmon