apiVersion: batch/v1
kind: CronJob
metadata:
  name: trigger-universe-types
spec:
  schedule: "10 23 * * *" #	Run @ 11:10PM UTC
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: trigger
              image: quay.io/curl/curl:8.5.0
              imagePullPolicy: IfNotPresent
              command:
                - curl
                - "-vvv"
                - "http://scheduler:3333/universe/types"
          restartPolicy: Never