// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAllianceIcon = "alliance_icon"

// AllianceIcon mapped from table <alliance_icon>
type AllianceIcon struct {
	ID        int32  `gorm:"column:id;primaryKey" json:"id"`
	Px128x128 string `gorm:"column:px128x128;not null" json:"px128x128"`
	Px64x64   string `gorm:"column:px64x64;not null" json:"px64x64"`
}

// TableName AllianceIcon's table name
func (*AllianceIcon) TableName() string {
	return TableNameAllianceIcon
}
