// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCharacterPortrait = "character_portrait"

// CharacterPortrait mapped from table <character_portrait>
type CharacterPortrait struct {
	ID        int32  `gorm:"column:id;primaryKey" json:"id"`
	Px128x128 string `gorm:"column:px128x128;not null" json:"px128x128"`
	Px256x256 string `gorm:"column:px256x256;not null" json:"px256x256"`
	Px512x512 string `gorm:"column:px512x512;not null" json:"px512x512"`
	Px64x64   string `gorm:"column:px64x64;not null" json:"px64x64"`
}

// TableName CharacterPortrait's table name
func (*CharacterPortrait) TableName() string {
	return TableNameCharacterPortrait
}
