// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCharacter = "character"

// Character mapped from table <character>
type Character struct {
	ID             int32     `gorm:"column:id;primaryKey" json:"id"`
	AllianceID     *int32    `gorm:"column:alliance_id" json:"alliance_id"`
	Birthday       time.Time `gorm:"column:birthday;not null" json:"birthday"`
	BloodlineID    int32     `gorm:"column:bloodline_id;not null" json:"bloodline_id"`
	CorporationID  int32     `gorm:"column:corporation_id;not null" json:"corporation_id"`
	Description    *string   `gorm:"column:description" json:"description"`
	FactionID      *int32    `gorm:"column:faction_id" json:"faction_id"`
	Gender         string    `gorm:"column:gender;not null" json:"gender"`
	Name           string    `gorm:"column:name;not null" json:"name"`
	RaceID         int32     `gorm:"column:race_id;not null" json:"race_id"`
	SecurityStatus *float64  `gorm:"column:security_status" json:"security_status"`
	Title          *string   `gorm:"column:title" json:"title"`
}

// TableName Character's table name
func (*Character) TableName() string {
	return TableNameCharacter
}
