// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameContractBid = "contract_bid"

// ContractBid mapped from table <contract_bid>
type ContractBid struct {
	ID      int64     `gorm:"column:id;primaryKey" json:"id"`
	Amount  float64   `gorm:"column:amount;not null" json:"amount"`
	BidID   int32     `gorm:"column:bid_id;primaryKey" json:"bid_id"`
	DateBid time.Time `gorm:"column:date_bid;not null" json:"date_bid"`
}

// TableName ContractBid's table name
func (*ContractBid) TableName() string {
	return TableNameContractBid
}
