// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCorporationAllianceHistory = "corporation_alliance_history"

// CorporationAllianceHistory mapped from table <corporation_alliance_history>
type CorporationAllianceHistory struct {
	ID         int32     `gorm:"column:id;primaryKey" json:"id"`
	AllianceID int32     `gorm:"column:alliance_id;not null" json:"alliance_id"`
	IsDeleted  bool      `gorm:"column:is_deleted;not null" json:"is_deleted"`
	RecordID   int32     `gorm:"column:record_id;primaryKey" json:"record_id"`
	StartDate  time.Time `gorm:"column:start_date;not null" json:"start_date"`
}

// TableName CorporationAllianceHistory's table name
func (*CorporationAllianceHistory) TableName() string {
	return TableNameCorporationAllianceHistory
}
