// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameKillmailStat = "killmail_stats"

// KillmailStat mapped from table <killmail_stats>
type KillmailStat struct {
	ID             int64   `gorm:"column:id;primaryKey" json:"id"`
	LocationID     int32   `gorm:"column:location_id;not null" json:"location_id"`
	Hash           string  `gorm:"column:hash;not null" json:"hash"`
	FittedValue    float64 `gorm:"column:fitted_value;not null" json:"fitted_value"`
	DestroyedValue float64 `gorm:"column:destroyed_value;not null" json:"destroyed_value"`
	DroppedValue   float64 `gorm:"column:dropped_value;not null" json:"dropped_value"`
	Href           string  `gorm:"column:href;not null" json:"href"`
}

// TableName KillmailStat's table name
func (*KillmailStat) TableName() string {
	return TableNameKillmailStat
}
