// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMarketOrder = "market_orders"

// MarketOrder mapped from table <market_orders>
type MarketOrder struct {
	ID           int64     `gorm:"column:id;primaryKey" json:"id"`
	TypeID       int32     `gorm:"column:type_id;not null" json:"type_id"`
	RegionID     int32     `gorm:"column:region_id;not null" json:"region_id"`
	LocationID   int64     `gorm:"column:location_id;not null" json:"location_id"`
	Range        string    `gorm:"column:range;not null" json:"range"`
	IsBuyOrder   bool      `gorm:"column:is_buy_order;not null" json:"is_buy_order"`
	Price        float64   `gorm:"column:price;not null" json:"price"`
	VolumeTotal  int32     `gorm:"column:volume_total;not null" json:"volume_total"`
	VolumeRemain int32     `gorm:"column:volume_remain;not null" json:"volume_remain"`
	Issued       time.Time `gorm:"column:issued;not null" json:"issued"`
	Duration     int32     `gorm:"column:duration;not null" json:"duration"`
	MinVolume    int32     `gorm:"column:min_volume;not null" json:"min_volume"`
	LastUpdated  time.Time `gorm:"column:last_updated;not null" json:"last_updated"`
	IsActive     bool      `gorm:"column:is_active;not null;default:true" json:"is_active"`
}

// TableName MarketOrder's table name
func (*MarketOrder) TableName() string {
	return TableNameMarketOrder
}
