// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMarketHistory = "market_history"

// MarketHistory mapped from table <market_history>
type MarketHistory struct {
	TypeID     int32     `gorm:"column:type_id;primaryKey" json:"type_id"`
	RegionID   int32     `gorm:"column:region_id;primaryKey" json:"region_id"`
	Date       time.Time `gorm:"column:date;primaryKey" json:"date"`
	Average    float64   `gorm:"column:average;not null" json:"average"`
	Highest    float64   `gorm:"column:highest;not null" json:"highest"`
	Lowest     float64   `gorm:"column:lowest;not null" json:"lowest"`
	OrderCount int32     `gorm:"column:order_count;not null" json:"order_count"`
	Volume     int64     `gorm:"column:volume;not null" json:"volume"`
}

// TableName MarketHistory's table name
func (*MarketHistory) TableName() string {
	return TableNameMarketHistory
}
