// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUniverseStationService = "universe_station_service"

// UniverseStationService mapped from table <universe_station_service>
type UniverseStationService struct {
	StationID int32  `gorm:"column:station_id;primaryKey" json:"station_id"`
	Service   string `gorm:"column:service;primaryKey" json:"service"`
}

// TableName UniverseStationService's table name
func (*UniverseStationService) TableName() string {
	return TableNameUniverseStationService
}
