// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUniverseStargate = "universe_stargate"

// UniverseStargate mapped from table <universe_stargate>
type UniverseStargate struct {
	ID                    int32   `gorm:"column:id;primaryKey" json:"id"`
	Name                  string  `gorm:"column:name;not null" json:"name"`
	DestinationStargateID int32   `gorm:"column:destination_stargate_id;not null" json:"destination_stargate_id"`
	DestinationSystemID   int32   `gorm:"column:destination_system_id;not null" json:"destination_system_id"`
	PositionX             float64 `gorm:"column:position_x;not null" json:"position_x"`
	PositionY             float64 `gorm:"column:position_y;not null" json:"position_y"`
	PositionZ             float64 `gorm:"column:position_z;not null" json:"position_z"`
	TypeID                int32   `gorm:"column:type_id;not null" json:"type_id"`
}

// TableName UniverseStargate's table name
func (*UniverseStargate) TableName() string {
	return TableNameUniverseStargate
}
