// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUniverseTypeDogmaAttribute = "universe_type_dogma_attribute"

// UniverseTypeDogmaAttribute mapped from table <universe_type_dogma_attribute>
type UniverseTypeDogmaAttribute struct {
	TypeID      int32   `gorm:"column:type_id;primaryKey" json:"type_id"`
	AttributeID int32   `gorm:"column:attribute_id;primaryKey" json:"attribute_id"`
	Value       float64 `gorm:"column:value;not null" json:"value"`
}

// TableName UniverseTypeDogmaAttribute's table name
func (*UniverseTypeDogmaAttribute) TableName() string {
	return TableNameUniverseTypeDogmaAttribute
}
