// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUniverseSystemKill = "universe_system_kill"

// UniverseSystemKill mapped from table <universe_system_kill>
type UniverseSystemKill struct {
	SystemID  int32     `gorm:"column:system_id;primaryKey" json:"system_id"`
	Timestamp time.Time `gorm:"column:timestamp;primaryKey;default:'2023-12-24 07:52:35.721871+00'::timestamp with time zone" json:"timestamp"`
	ShipKills int32     `gorm:"column:ship_kills;not null" json:"ship_kills"`
	PodKills  int32     `gorm:"column:pod_kills;not null" json:"pod_kills"`
	NpcKills  int32     `gorm:"column:npc_kills;not null" json:"npc_kills"`
}

// TableName UniverseSystemKill's table name
func (*UniverseSystemKill) TableName() string {
	return TableNameUniverseSystemKill
}
