// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUniverseRegion = "universe_region"

// UniverseRegion mapped from table <universe_region>
type UniverseRegion struct {
	ID          int32   `gorm:"column:id;primaryKey" json:"id"`
	Name        string  `gorm:"column:name;not null" json:"name"`
	Description *string `gorm:"column:description" json:"description"`
}

// TableName UniverseRegion's table name
func (*UniverseRegion) TableName() string {
	return TableNameUniverseRegion
}
