// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUniverseType = "universe_type"

// UniverseType mapped from table <universe_type>
type UniverseType struct {
	ID             int32    `gorm:"column:id;primaryKey" json:"id"`
	Name           string   `gorm:"column:name;not null" json:"name"`
	Description    string   `gorm:"column:description;not null" json:"description"`
	Capacity       *float64 `gorm:"column:capacity" json:"capacity"`
	GraphicID      *int32   `gorm:"column:graphic_id" json:"graphic_id"`
	GroupID        int32    `gorm:"column:group_id;not null" json:"group_id"`
	IconID         *int32   `gorm:"column:icon_id" json:"icon_id"`
	MarketGroupID  *int32   `gorm:"column:market_group_id" json:"market_group_id"`
	Mass           *float64 `gorm:"column:mass" json:"mass"`
	PackagedVolume *float64 `gorm:"column:packaged_volume" json:"packaged_volume"`
	PortionSize    *int32   `gorm:"column:portion_size" json:"portion_size"`
	Published      bool     `gorm:"column:published;not null" json:"published"`
	Radius         *float64 `gorm:"column:radius" json:"radius"`
	Volume         *float64 `gorm:"column:volume" json:"volume"`
}

// TableName UniverseType's table name
func (*UniverseType) TableName() string {
	return TableNameUniverseType
}
