// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUniverseGraphic = "universe_graphics"

// UniverseGraphic mapped from table <universe_graphics>
type UniverseGraphic struct {
	ID            int32   `gorm:"column:id;not null" json:"id"`
	CollisionFile *string `gorm:"column:collision_file" json:"collision_file"`
	GraphicFile   *string `gorm:"column:graphic_file" json:"graphic_file"`
	IconFolder    *string `gorm:"column:icon_folder" json:"icon_folder"`
	SofDna        *string `gorm:"column:sof_dna" json:"sof_dna"`
	SofFationName *string `gorm:"column:sof_fation_name" json:"sof_fation_name"`
	SofHullName   *string `gorm:"column:sof_hull_name" json:"sof_hull_name"`
	SofRaceName   *string `gorm:"column:sof_race_name" json:"sof_race_name"`
}

// TableName UniverseGraphic's table name
func (*UniverseGraphic) TableName() string {
	return TableNameUniverseGraphic
}
