// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUniverseGroup = "universe_group"

// UniverseGroup mapped from table <universe_group>
type UniverseGroup struct {
	ID         int32  `gorm:"column:id;primaryKey" json:"id"`
	CategoryID int32  `gorm:"column:category_id;not null" json:"category_id"`
	Name       string `gorm:"column:name;not null" json:"name"`
	Published  bool   `gorm:"column:published;not null" json:"published"`
}

// TableName UniverseGroup's table name
func (*UniverseGroup) TableName() string {
	return TableNameUniverseGroup
}
