// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUniverseStructure = "universe_structure"

// UniverseStructure mapped from table <universe_structure>
type UniverseStructure struct {
	ID            int64   `gorm:"column:id;primaryKey" json:"id"`
	Name          string  `gorm:"column:name;not null" json:"name"`
	OwnerID       int32   `gorm:"column:owner_id;not null" json:"owner_id"`
	PositionX     float64 `gorm:"column:position_x;not null" json:"position_x"`
	PositionY     float64 `gorm:"column:position_y;not null" json:"position_y"`
	PositionZ     float64 `gorm:"column:position_z;not null" json:"position_z"`
	SolarSystemID int32   `gorm:"column:solar_system_id;not null" json:"solar_system_id"`
	TypeID        int32   `gorm:"column:type_id;not null" json:"type_id"`
}

// TableName UniverseStructure's table name
func (*UniverseStructure) TableName() string {
	return TableNameUniverseStructure
}
