// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUniverseBloodline = "universe_bloodlines"

// UniverseBloodline mapped from table <universe_bloodlines>
type UniverseBloodline struct {
	ID            int32  `gorm:"column:id;primaryKey" json:"id"`
	CorporationID int32  `gorm:"column:corporation_id;not null" json:"corporation_id"`
	Description   string `gorm:"column:description;not null" json:"description"`
	RaceID        int32  `gorm:"column:race_id;not null" json:"race_id"`
	ShipTypeID    int32  `gorm:"column:ship_type_id;not null" json:"ship_type_id"`
	Charisma      int32  `gorm:"column:charisma;not null" json:"charisma"`
	Intelligence  int32  `gorm:"column:intelligence;not null" json:"intelligence"`
	Memory        int32  `gorm:"column:memory;not null" json:"memory"`
	Perception    int32  `gorm:"column:perception;not null" json:"perception"`
	Willpower     int32  `gorm:"column:willpower;not null" json:"willpower"`
}

// TableName UniverseBloodline's table name
func (*UniverseBloodline) TableName() string {
	return TableNameUniverseBloodline
}
