// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUniverseRace = "universe_race"

// UniverseRace mapped from table <universe_race>
type UniverseRace struct {
	ID          int32  `gorm:"column:id;primaryKey" json:"id"`
	AllianceID  int32  `gorm:"column:alliance_id;not null" json:"alliance_id"`
	Description string `gorm:"column:description;not null" json:"description"`
	Name        string `gorm:"column:name;not null" json:"name"`
}

// TableName UniverseRace's table name
func (*UniverseRace) TableName() string {
	return TableNameUniverseRace
}
