// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUniverseConstellation = "universe_constellation"

// UniverseConstellation mapped from table <universe_constellation>
type UniverseConstellation struct {
	ID        int32   `gorm:"column:id;primaryKey" json:"id"`
	Name      string  `gorm:"column:name;not null" json:"name"`
	RegionID  int32   `gorm:"column:region_id;not null" json:"region_id"`
	PositionX float64 `gorm:"column:position_x;not null" json:"position_x"`
	PositionY float64 `gorm:"column:position_y;not null" json:"position_y"`
	PositionZ float64 `gorm:"column:position_z;not null" json:"position_z"`
}

// TableName UniverseConstellation's table name
func (*UniverseConstellation) TableName() string {
	return TableNameUniverseConstellation
}
