// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUniversePlanet = "universe_planet"

// UniversePlanet mapped from table <universe_planet>
type UniversePlanet struct {
	ID        int32   `gorm:"column:id;primaryKey" json:"id"`
	SystemID  int32   `gorm:"column:system_id;not null" json:"system_id"`
	Name      string  `gorm:"column:name;not null" json:"name"`
	PositionX float64 `gorm:"column:position_x;not null" json:"position_x"`
	PositionY float64 `gorm:"column:position_y;not null" json:"position_y"`
	PositionZ float64 `gorm:"column:position_z;not null" json:"position_z"`
	TypeID    int32   `gorm:"column:type_id;not null" json:"type_id"`
}

// TableName UniversePlanet's table name
func (*UniversePlanet) TableName() string {
	return TableNameUniversePlanet
}
