name: Apply Database Migrations

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'migrations/*'

permissions:
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Atlas
        uses: ariga/setup-atlas@v0.2.8
        with:
          cloud-token: ${{ secrets.ATLAS_CLOUD_TOKEN }}
      - run: atlas version
      - uses: ariga/atlas-action/migrate/lint@v0.2.8
        with:
          dir: 'file://migrations'
          dir-name: 'evebot' # The name of the project in Atlas Cloud
          dev-url: "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable"
      - uses: ariga/atlas-action/migrate/push@v0.2.8
        if: github.ref == 'refs/heads/main'
        with:
          dir: 'file://migrations'
          dir-name: 'evebot'
          dev-url: "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable"