name: Unit Tests

on:
  push:
    branches-ignore:
      - release-please*
  pull_request:
    branches-ignore:
      - release-please*

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      mongo:
        image: mongo
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: evetools
          MONGO_INITDB_ROOT_PASSWORD: evetools
          MONGO_INITDB_DATABASE: evetools
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go 1.21.x
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.x
      - name: Install dependencies
        run: go mod download
      - name: Run tests
        run: go test -v ./...
      - name: Build Services
        run: go build -o ./builds/ -v ./cmd/...